#!/bin/sh

#export PATH="$HOME/.local/bin:$PATH"
#export PATH="$PATH:${$(find ~/.local/bin -maxdepth 1 -type d -printf %p:)%%:}"

# make caps hyper key
# setxkbmap -option caps:hyper &

#transmission-daemon
transmission-daemon --no-auth &

# disable x-shaped cursor in bspwm
/bin/xsetroot -cursor_name left_ptr

#enable numlock
numlockx off &

exec bspwm
#exec /usr/bin/cinnamon
